---
  - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
    wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      search_regex: OpenSSH
      delay: 30
      timeout: 600
      sleep: 30
    connection: local

  - name: install python on ubuntu
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python3)
    register: task_result
    until: task_result.rc == 0
    retries: 5
    delay: 30

  - name: install java on ubuntu
    raw: (sudo apt -y update && sudo apt install -y default-jre)
    register: task_result
    until: task_result.rc == 0
    retries: 5
    delay: 30

    
  
  # Disabling for Amazon Linux 2 as selinux is disabled by default.
  - name: Disable the selinux
    selinux:
      state: disabled
    when: (ansible_distribution != "Ubuntu") and (ansible_distribution != "Amazon")

  - name: Install ansible
    import_tasks: install_ansible.yml

  - name: Tune the system settings
    import_tasks: tune.yml
  
  - name: include opensearch installation
    include: opensearch.yml
  
  - name: include security plugin for opensearch
    include: security.yml
  
