---
cluster_name: test
cluster_hostname: test-cluster.aws
cluster_ip_address: 10.0.0.1
node_machine_type_identifier: m5-12xlarge
total_nodes_count: 5
active_data_nodes: 4
master_eligible_nodes_count: 1
index_count: 100
#shards_per_index: 5 
primary_shards_per_index: 5
replica_shards_per_index: 5
#total_shards_per_index: primary_shards_per_index * (1 + replica_shards_per_index)
index_roll_over_size_gb: 50
index_clean_up_age_days: 20
#node_disk_volume_gb: 100 # discuss effect of node addition/removal
simulation_frequency_minutes: 5

# Specify data ingestion with respect to time of the day to represent pattern for entire day(24hrs).
states:
- position: 1
  time_hh_mm_ss: '00_00_00'
  ingestion_rate_gb_per_hr: 10
  searches:
    simple: 35
    complex: 2
- position: 2
  time_hh_mm_ss: '06_00_00'
  ingestion_rate_gb_per_hr: 60
  searches:
    simple: 40
    medium: 30
    complex: 10
- position: 3
  time_hh_mm_ss: '12_00_00'
  ingestion_rate_gb_per_hr: 65
  searches:
    simple: 60
    medium: 40
    complex: 15
- position: 4
  time_hh_mm_ss: '18_00_00'
  ingestion_rate_gb_per_hr: 15
  searches:
    simple: 55
    medium: 25
    complex: 5
- position: 5
  time_hh_mm_ss: '23_00_00'
  ingestion_rate_gb_per_hr: 5
  searches:
    simple: 40
    medium: 30
    complex: 10
randomness_percentage: 5


# Specify searches along with their type, probability and load inflected on the cluster.
search_description:
  simple:
    cpu_load_percent: 10
    memory_load_percent: 10
    heap_load_percent: 5
  medium:
    cpu_load_percent: 20
    memory_load_percent: 20
    heap_load_percent: 15
  complex:
    cpu_load_percent: 30
    memory_load_percent: 30
    heap_load_percent: 25
 